modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/sabu8190/Mekanism-Optimizer/issues"

[[mods]]
modId="mekanism_optimizer"
version="1.0.6"
displayName="Mekanism Optimizer"
updateJSONURL="https://github.com/sabu8190/Mekanism-Optimizer/releases"
displayURL="https://github.com/sabu8190/Mekanism-Optimizer"
logoFile="logo.png"
credits="Mekanism Team, SpongePowered Mixin, Minecraft Forge"
authors="Antigravity"
description='''High-performance optimization mod for Mekanism logistical pipes, transporter simulations, dedicated file logger, and burst auto-eject.'''

[[dependencies.mekanism_optimizer]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekanism_optimizer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekanism_optimizer]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.4.0,)"
    ordering="AFTER"
    side="BOTH"
